name: Azure Login with Service Principal

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Grant write permissions for id-token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CLIENT_SECRET }} # Alternatively, you can use this if you prefer a single JSON object.

      - name: Run Azure CLI commands
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
