name: Dispatch Terraform Workflow

on:
  workflow_dispatch: # Manual trigger

permissions:
  id-token: write  # Grant write permissions for id-token

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master # Ensure you're on the master branch

    # Step 2: Set up Azure CLI
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 # Replace with the desired version
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

    # Step 4: Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: module

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: module

    # Step 6: Terraform Apply (Manual Approval Required)
    - name: Terraform Apply
      if: ${{ github.event.inputs.auto_apply != 'true' }}
      run: terraform apply -auto-approve tfplan
      working-directory: module
